/**
 * Animated burned-in captions (ASS/libass) for the final render.
 *
 * Narration sections become short caption cues (chunked to a few words so
 * lines stay punchy), timed on the output timeline, and styled per the
 * channel's caption_style token:
 *   - minimal:    small clean white, soft fade
 *   - standard:   bold white with outline, fade in/out
 *   - expressive: bold brass highlight with a pop-in scale animation
 *
 * Pure string generation — fully unit-testable; ffmpeg burns the result via
 * the `ass` filter (libass ships with Debian's ffmpeg).
 */

export type CaptionSection = {
  text: string;
  /** Output-timeline position where the narration starts. */
  startMs: number;
  /** Room the narration has before the next one begins. */
  maxDurationMs: number;
};

export type CaptionCue = {
  text: string;
  startMs: number;
  endMs: number;
};

const MAX_WORDS_PER_CUE = 6;
const MIN_CUE_MS = 700;
/** Spoken pace used to estimate how long the section is actually audible. */
const WORDS_PER_SECOND = 2.3;

/**
 * Splits each narration section into short sequential cues, allocating the
 * section's (estimated) spoken duration across cues by word count.
 */
export function buildCaptionCues(sections: CaptionSection[]): CaptionCue[] {
  const cues: CaptionCue[] = [];

  for (const section of sections) {
    const words = section.text
      .replace(/\s+/g, " ")
      .trim()
      .split(" ")
      .filter(Boolean);
    if (words.length === 0) continue;

    const spokenMs = Math.min(
      Math.max(section.maxDurationMs, MIN_CUE_MS),
      Math.round((words.length / WORDS_PER_SECOND) * 1000) + 400,
    );

    const chunks: string[] = [];
    for (let i = 0; i < words.length; i += MAX_WORDS_PER_CUE) {
      chunks.push(words.slice(i, i + MAX_WORDS_PER_CUE).join(" "));
    }

    let position = section.startMs;
    const perWordMs = spokenMs / words.length;
    for (const chunk of chunks) {
      const chunkWords = chunk.split(" ").length;
      const duration = Math.max(MIN_CUE_MS, Math.round(chunkWords * perWordMs));
      const endMs = Math.min(
        section.startMs + section.maxDurationMs,
        position + duration,
      );
      if (endMs <= position) break;
      cues.push({ text: chunk, startMs: Math.round(position), endMs });
      position = endMs;
    }
  }

  return cues.sort((a, b) => a.startMs - b.startMs);
}

function assTime(ms: number): string {
  const clamped = Math.max(0, ms);
  const cs = Math.round(clamped / 10);
  const h = Math.floor(cs / 360_000);
  const m = Math.floor((cs % 360_000) / 6_000);
  const s = Math.floor((cs % 6_000) / 100);
  const rest = cs % 100;
  return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(rest).padStart(2, "0")}`;
}

/** ASS text escaping: braces would open override blocks; newlines break cues. */
function escapeAssText(text: string): string {
  return text.replace(/[{}]/g, "").replace(/[\r\n]+/g, " ").trim();
}

type StyleSpec = {
  fontSize: number;
  primaryColour: string;
  outlineColour: string;
  outline: number;
  shadow: number;
  bold: number;
  marginV: number;
  /** Per-cue override tags (animation); {} block prepended to the text. */
  animation: string;
};

/** ASS colours are &HAABBGGRR (alpha first, blue-green-red order). */
function styleFor(captionStyle: string): StyleSpec {
  switch (captionStyle) {
    case "minimal":
      return {
        fontSize: 44,
        primaryColour: "&H00FFFFFF",
        outlineColour: "&HA0000000",
        outline: 2,
        shadow: 0,
        bold: 0,
        marginV: 56,
        animation: "{\\fad(120,120)}",
      };
    case "expressive":
      return {
        fontSize: 58,
        // Creator brass (#d8b866) → BGR 66 B8 D8.
        primaryColour: "&H0066B8D8",
        outlineColour: "&HB4000000",
        outline: 3,
        shadow: 1,
        bold: 1,
        marginV: 64,
        // Fade + quick pop from 82% to 100% scale.
        animation:
          "{\\fad(100,120)\\fscx82\\fscy82\\t(0,130,\\fscx100\\fscy100)}",
      };
    default: // standard
      return {
        fontSize: 52,
        primaryColour: "&H00FFFFFF",
        outlineColour: "&HB4000000",
        outline: 3,
        shadow: 1,
        bold: 1,
        marginV: 60,
        animation: "{\\fad(120,140)}",
      };
  }
}

/**
 * Builds the complete ASS document for the given cues. PlayRes is fixed at
 * 1920×1080 with ScaledBorderAndShadow, so libass scales cleanly to whatever
 * the actual render resolution is (including the 720p proxy fallback).
 */
export function buildAssDocument(
  cues: CaptionCue[],
  captionStyle: string,
): string {
  const style = styleFor(captionStyle);

  const header = [
    "[Script Info]",
    "; Generated by Creator — burned-in narration captions.",
    "ScriptType: v4.00+",
    "PlayResX: 1920",
    "PlayResY: 1080",
    "ScaledBorderAndShadow: yes",
    "WrapStyle: 2",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Creator,DejaVu Sans,${style.fontSize},${style.primaryColour},&H000000FF,${style.outlineColour},&H96000000,${style.bold ? -1 : 0},0,0,0,100,100,0,0,1,${style.outline},${style.shadow},2,96,96,${style.marginV},1`,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ];

  const events = cues.map((cue) => {
    const text = escapeAssText(cue.text);
    return `Dialogue: 0,${assTime(cue.startMs)},${assTime(cue.endMs)},Creator,,0,0,0,,${style.animation}${text}`;
  });

  return [...header, ...events, ""].join("\n");
}
